# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'BikeLocationGeekhub' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
    pod 'GoogleMaps', '~> 2.2'
    pod 'Firebase/Core'
    pod 'Firebase/Auth'
    pod 'FirebaseUI', '~> 2.0'
end
